<script setup lang="ts">
import { Suit } from "../types"

defineProps<{
  color: string
  suit: Suit
  suitId: string
}>()
</script>

<template>
  <template v-if="suit === '♠'">
    <use
      :xlink:href="suitId"
      fill="black"
      height="11.4"
      width="11.4"
      transform="translate(-26,-56)scale(1,0.972)rotate(-10)"
    ></use>
    <use
      :xlink:href="suitId"
      fill="black"
      height="11.4"
      width="11.4"
      transform="translate(-22,-38)scale(1,0.972)rotate(-5)"
    ></use>
    <use
      :xlink:href="suitId"
      fill="black"
      height="11.4"
      width="11.4"
      transform="translate(20,-53)scale(1,0.972)rotate(20)"
    ></use>
    <use
      :xlink:href="suitId"
      fill="black"
      height="11.4"
      width="11.4"
      transform="translate(14.5,-39)scale(1,0.972)rotate(15)"
    ></use>
  </template>
  <template v-else-if="suit === '♥'">
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(47.5,-32)scale(1,0.972)rotate(85)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(41.5,-46)scale(1,0.972)rotate(60)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(48.5,-16)scale(1,0.972)rotate(110)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(43,-1)scale(1,0.972)rotate(130)"
    ></use>
  </template>
  <template v-else-if="suit === '♣'">
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(25.5,-24.25)scale(1,0.972)rotate(5)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(31,-42.25)scale(1,0.972)rotate(15)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(40,-57.9)scale(1,0.972)rotate(25)"
    ></use>
  </template>
  <template v-else-if="suit === '♦'">
    <use
      :xlink:href="suitId"
      :fill="color"
      height="15.21"
      width="15.21"
      transform="translate(-7.61,-7.5)scale(1,0.972)rotate(0)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="15.21"
      width="15.21"
      transform="translate(-17.75,-7.5)scale(1,0.972)rotate(0)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="22.82"
      width="22.82"
      transform="translate(-46,-58.03)scale(1,0.972)rotate(-15)"
      stroke="#44F"
      stroke-width="42.352"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="19.02"
      width="19.02"
      transform="translate(-38.5,-40.42)scale(1,0.972)rotate(-10)"
      stroke="#44F"
      stroke-width="48"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="16.48"
      width="16.48"
      transform="translate(-34,-23.47)scale(1,0.972)rotate(-5)"
      stroke="#44F"
      stroke-width="55.384"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="13.94"
      width="13.94"
      transform="translate(-31.5,-9.52)scale(1,0.972)rotate(0)"
      stroke="#44F"
      stroke-width="65.454"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="12.68"
      width="12.68"
      transform="translate(-31,2.61)scale(1,0.972)rotate(10)"
      stroke="#44F"
      stroke-width="72"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(79,-7)scale(1,0.972)rotate(60)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(66.6,-1)scale(1,0.972)rotate(50)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(55.5,8.5)scale(1,0.972)rotate(40)"
    ></use>
    <use
      :xlink:href="suitId"
      :fill="color"
      height="11.4"
      width="11.4"
      transform="translate(47,19.5)scale(1,0.972)rotate(30)"
    ></use>
  </template>
</template>
